version: '3'
services:
  web:
    build: .
    image: mportela/swplanetapi:latest
    command: python -u app.py
    volumes:
        - .:/app
    ports:
        - "5000:5000"
    links:
        - mongodb
  mongodb:
    image: "mongo:3.6"
